name: Build for Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        vcpkg integrate install
        vcpkg install vcpkg-cmake:x86-windows
        vcpkg install vcpkg-cmake-config:x86-windows
        vcpkg install libtomcrypt:x86-windows

    - name: Show path
      run: |
        ls -R ${{github.workspace}}
        echo $env:VCPKG_INSTALLATION_ROOT
      shell: pwsh

    - name: Set environmental variables
      shell: pwsh
      run: |
        echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mobileqq-flash-photo-cracker
        path: ${{github.workspace}}/build/fp_cracker.exe
        retention-days: 7
